import 'package:flutter_test/flutter_test.dart';

import 'test_helpers/source_scan.dart';

/// The whole app must consume project code through the generated barrel only.
///
/// `lib/all_imports.dart` is regenerated by `tool/generate_imports.dart` and
/// already exports every project file, so granular `package:justus/...` imports
/// are pure duplication: they hide dependencies and break whenever a symbol
/// moves to another file.
const String _barrelImport = "package:justus/all_imports.dart";

/// Files that cannot import the barrel without creating a cycle.
const Set<String> _barrelHostile = <String>{
  'lib/all_imports.dart',
  'lib/core/theme/app_category_colors.dart',
  'lib/core/theme/app_dimens.dart',
  'lib/core/theme/app_palette.dart',
  'lib/core/theme/app_radius.dart',
  'lib/core/theme/app_theme.dart',
};

/// Files that legitimately depend on nothing from `lib/`: they hold constants,
/// plain data models, framework glue or machine-generated code. Importing the
/// barrel there would only trigger `unused_import`.
const Set<String> _standalone = <String>{
  // Barrels / generated code
  'lib/shared/design_system/design_system.dart',
  'lib/firebase_options.dart',
  // Constants, models and framework glue with no project dependency
  'lib/core/localization/language_helper.dart',
  'lib/core/local_storage/cache_service.dart',
  'lib/core/media/compression_service.dart',
  'lib/core/network/api_config.dart',
  'lib/core/network/api_routes.dart',
  'lib/core/network/result_wrapper.dart',
  'lib/core/realtime/realtime_table_binding.dart',
  'lib/core/realtime/trailing_edge_debounce.dart',
  'lib/core/theme/theme_provider.dart',
  'lib/core/utils/ansi_logger.dart',
  'lib/core/version/version_models.dart',
  'lib/features/auth/auth_models.dart',
  'lib/features/drive/drive_models.dart',
  'lib/features/games/game_models.dart',
  'lib/features/mood/mood_models.dart',
  'lib/shared/utils/date/app_date_utils.dart',
  'lib/shared/utils/extensions/supabase_query_extensions.dart',
  'lib/shared/utils/row/row_utils.dart',
  'lib/shared/widgets/tab_screen.dart',
};

final RegExp _importRegex = RegExp(
  r'''^\s*(?:import|export)\s+['"]([^'"]+)['"]''',
  multiLine: true,
);

bool _isGenerated(String path) =>
    normalizePath(path).startsWith('lib/core/localization/generated/');

void main() {
  test('lib/ only imports project code through all_imports.dart', () {
    final violations = <String>[];
    var scanned = 0;

    for (final file in dartFilesUnder(resolveLibDir())) {
      final path = normalizePath(file.path);
      if (_barrelHostile.contains(path) || _isGenerated(path)) {
        continue;
      }
      scanned++;

      for (final match in _importRegex.allMatches(file.readAsStringSync())) {
        final uri = match.group(1)!;
        if (!uri.startsWith('package:justus/') || uri == _barrelImport) {
          continue;
        }
        violations.add("$path imports '$uri' — use '$_barrelImport' instead.");
      }
    }

    expect(scanned, greaterThan(50),
        reason: 'Only $scanned files scanned — wrong directory?');
    expect(
      violations,
      isEmpty,
      reason: 'Granular package:justus/ imports found (${violations.length}).\n'
          '${violations.join('\n')}',
    );
  });

  test('lib/ files that need project code import the barrel', () {
    final missing = <String>[];
    var scanned = 0;

    for (final file in dartFilesUnder(resolveLibDir())) {
      final path = normalizePath(file.path);
      if (_barrelHostile.contains(path) ||
          _standalone.contains(path) ||
          _isGenerated(path)) {
        continue;
      }
      scanned++;

      if (!file.readAsStringSync().contains(_barrelImport)) {
        missing.add('$path has no import \'$_barrelImport\'; — add it, or if '
            'the file really has no project dependency, list it in '
            '_standalone with a short reason.');
      }
    }

    expect(scanned, greaterThan(50),
        reason: 'Only $scanned files scanned — wrong directory?');
    expect(
      missing,
      isEmpty,
      reason: 'Files missing the barrel import (${missing.length}).\n'
          '${missing.join('\n')}',
    );
  });
}
