// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwH525W1W0__LDVAd-Rhzwz6037WVlFrA',
    appId: '1:930566996594:web:2d200f1a0d0cc7d8d078eb',
    messagingSenderId: '930566996594',
    projectId: 'justus-9888d',
    authDomain: 'justus-9888d.firebaseapp.com',
    storageBucket: 'justus-9888d.firebasestorage.app',
    measurementId: 'G-LCTHV6548K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfJJZIla9NtJb_kjOPs1HB9Zs9f_-g4k0',
    appId: '1:930566996594:android:65335cde59780ef3d078eb',
    messagingSenderId: '930566996594',
    projectId: 'justus-9888d',
    storageBucket: 'justus-9888d.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEQrXJB7t6eWMBfwmyEc8EZI8ebtoys_s',
    appId: '1:930566996594:ios:02645a409ec31751d078eb',
    messagingSenderId: '930566996594',
    projectId: 'justus-9888d',
    storageBucket: 'justus-9888d.firebasestorage.app',
    iosBundleId: 'com.fezze.justus',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEQrXJB7t6eWMBfwmyEc8EZI8ebtoys_s',
    appId: '1:930566996594:ios:02645a409ec31751d078eb',
    messagingSenderId: '930566996594',
    projectId: 'justus-9888d',
    storageBucket: 'justus-9888d.firebasestorage.app',
    iosBundleId: 'com.fezze.justus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwH525W1W0__LDVAd-Rhzwz6037WVlFrA',
    appId: '1:930566996594:web:37cedfc3073976e6d078eb',
    messagingSenderId: '930566996594',
    projectId: 'justus-9888d',
    authDomain: 'justus-9888d.firebaseapp.com',
    storageBucket: 'justus-9888d.firebasestorage.app',
    measurementId: 'G-KPT17K9GGY',
  );
}
