CREATE TABLE "public"."drive_file_types" (
  "id"        bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "extension" text   NOT NULL,
  "mime_type" text,
  "icon_slug" text,
  CONSTRAINT "drive_file_types_extension_key" UNIQUE (EXTENSION),
  CONSTRAINT "drive_file_types_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."drive_file_types"
  ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read access" ON "public"."drive_file_types"
  FOR SELECT
  TO PUBLIC
  USING (true);

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."drive_file_types" TO "anon", "authenticated", "postgres", "service_role";
