CREATE TABLE "public"."emojis" (
  "id"         bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "emoji_char" text   NOT NULL,
  CONSTRAINT "emojis_emoji_char_key" UNIQUE (emoji_char),
  CONSTRAINT "emojis_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."emojis"
  ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can insert emojis" ON "public"."emojis"
  FOR INSERT
  TO "authenticated"
  WITH CHECK ((( SELECT auth.role() AS role) = 'authenticated'::text));

CREATE POLICY "Public read access" ON "public"."emojis"
  FOR SELECT
  TO PUBLIC
  USING (true);

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."emojis" TO "anon", "authenticated", "postgres", "service_role";
