CREATE TABLE "public"."permissions" (
  "id"          bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "slug"        text   NOT NULL,
  "description" text,
  CONSTRAINT "permissions_pkey" PRIMARY KEY (id),
  CONSTRAINT "permissions_slug_key" UNIQUE (slug)
);

ALTER TABLE "public"."permissions"
  ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read access" ON "public"."permissions"
  FOR SELECT
  TO PUBLIC
  USING (true);

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."permissions" TO "anon", "authenticated", "postgres", "service_role";
