CREATE TABLE "public"."roles_permissions" (
  "id"            bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "role_id"       bigint NOT NULL,
  "permission_id" bigint NOT NULL,
  CONSTRAINT "roles_permissions_permission_id_fkey" FOREIGN KEY (permission_id) REFERENCES public.permissions(id) ON DELETE CASCADE,
  CONSTRAINT "roles_permissions_pkey" PRIMARY KEY (id),
  CONSTRAINT "roles_permissions_role_id_fkey" FOREIGN KEY (role_id) REFERENCES public.roles(id) ON DELETE CASCADE,
  CONSTRAINT "roles_permissions_role_id_permission_id_key" UNIQUE (role_id, permission_id)
);

ALTER TABLE "public"."roles_permissions"
  ENABLE ROW LEVEL SECURITY;

CREATE INDEX idx_roles_permissions_permission_id ON public.roles_permissions USING btree (permission_id);

CREATE POLICY "Anyone can view roles permissions" ON "public"."roles_permissions"
  FOR SELECT
  TO PUBLIC
  USING (true);

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."roles_permissions" TO "anon", "authenticated", "postgres", "service_role";
