CREATE TABLE "public"."roles" (
  "id"   bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" text   NOT NULL,
  CONSTRAINT "roles_name_key" UNIQUE (name),
  CONSTRAINT "roles_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."roles"
  ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read access" ON "public"."roles"
  FOR SELECT
  TO PUBLIC
  USING (true);

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."roles" TO "anon", "authenticated", "postgres", "service_role";
