CREATE TABLE "public"."user_devices" (
  "id"           bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id"      integer,
  "user_agent"   text,
  "device_type"  text,
  "last_ip"      text,
  "created_at"   timestamp with time zone DEFAULT now(),
  "device_token" text,
  "updated_at"   timestamp with time zone DEFAULT now(),
  "locale"       text,
  CONSTRAINT "user_devices_device_token_key" UNIQUE (device_token),
  CONSTRAINT "user_devices_pkey" PRIMARY KEY (id),
  CONSTRAINT "user_devices_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE
);

ALTER TABLE "public"."user_devices"
  ENABLE ROW LEVEL SECURITY;

CREATE INDEX idx_user_devices_user_id ON public.user_devices USING btree (user_id);

CREATE TRIGGER update_user_devices_updated_at
  BEFORE UPDATE ON public.user_devices
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

CREATE POLICY "Users can delete their own devices" ON "public"."user_devices"
  FOR DELETE
  TO PUBLIC
  USING ((user_id = public.current_user_id()));

CREATE POLICY "Users can insert their own devices" ON "public"."user_devices"
  FOR INSERT
  TO PUBLIC
  WITH CHECK ((user_id = public.current_user_id()));

CREATE POLICY "Users can update their own devices" ON "public"."user_devices"
  FOR UPDATE
  TO PUBLIC
  USING ((user_id = public.current_user_id()))
  WITH CHECK ((user_id = public.current_user_id()));

CREATE POLICY "Users can view their own devices" ON "public"."user_devices"
  FOR SELECT
  TO PUBLIC
  USING ((user_id = public.current_user_id()));

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."user_devices" TO "anon", "authenticated", "postgres", "service_role";
